### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by ALETTERR** [architdate/PKHeX-Plugins#117]
Exception Details:
System.AggregateException: One or more errors occurred. ---> System.MissingMethodException: Method not found: 'PKHeX.Core.PIDType PKHeX.Core.PIDIV.get_Type()'.
   at PKHeX.Core.AutoMod.APILegality.ApplySetDetails(PKM pk, IBattleTemplate set, ITrainerInfo handler, IEncounterable enc, RegenSet regen)
   at PKHeX.Core.AutoMod.APILegality.GetLegalFromTemplate(ITrainerInfo dest, PKM template, IBattleTemplate set, LegalizationResult& satisfied)
   at PKHeX.Core.AutoMod.APILegality.<>c__DisplayClass90_0.<GetLegalFromTemplateTimeout>g__GetLegal|0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PKHeX.Core.AutoMod.APILegality.<TimeoutAfter>d__92.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at PKHeX.Core.AutoMod.APILegality.GetLegalFromTemplateTimeout(ITrainerInfo dest, PKM template, IBattleTemplate set, LegalizationResult& satisfied)
   at PKHeX.Core.AutoMod.Legalizer.TryAPIConvert(ITrainerInfo tr, IBattleTemplate set, PKM template, PKM& pkm)
   at PKHeX.Core.AutoMod.Legalizer.GetLegalFromSet(ITrainerInfo tr, IBattleTemplate set, PKM template, LegalizationResult& msg)
   at PKHeX.Core.AutoMod.Legalizer.ImportToExisting(SaveFile tr, IReadOnlyList`1 sets, IList`1 arr, List`1& invalidAPISets, List`1& timedoutSets, Int32 start, Boolean overwrite)
   at AutoModPlugins.ShowdownSetLoader.ImportSetsToBoxes(IReadOnlyList`1 sets, Boolean replace)
   at AutoModPlugins.ShowdownSetLoader.Import(IReadOnlyList`1 sets, Boolean skipDialog)
   at AutoModPlugins.URLGenning.URLGen(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.MissingMethodException: Method not found: 'PKHeX.Core.PIDType PKHeX.Core.PIDIV.get_Type()'.
   at PKHeX.Core.AutoMod.APILegality.ApplySetDetails(PKM pk, IBattleTemplate set, ITrainerInfo handler, IEncounterable enc, RegenSet regen)
   at PKHeX.Core.AutoMod.APILegality.GetLegalFromTemplate(ITrainerInfo dest, PKM template, IBattleTemplate set, LegalizationResult& satisfied)
   at PKHeX.Core.AutoMod.APILegality.<>c__DisplayClass90_0.<GetLegalFromTemplateTimeout>g__GetLegal|0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PKHeX.Core.AutoMod.APILegality.<TimeoutAfter>d__92.MoveNext()<---

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

PKHeX, Version=21.11.27.0, Culture=neutral, PublicKeyToken=null
D:\下载\PKHeX (211127)\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll

System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

System.Reflection, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Reflection\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Reflection.dll

System.Runtime.InteropServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.dll

Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed

System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll

System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll

System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.Windows.Forms.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\System.Windows.Forms.resources.dll

System.ValueTuple, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ValueTuple\v4.0_4.0.0.0__cc7b13ffcd2ddd51\System.ValueTuple.dll

AutoModPlugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
D:\下载\PKHeX (211127)\plugins\AutoModPlugins.dll

PKHeX.Core.Injection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

QRPlugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
D:\下载\PKHeX (211127)\plugins\QRPlugins.dll

PKHeX.Core.AutoMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

mscorlib.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\mscorlib.resources.dll

PKHeX.Core.Enhancements, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, b
![20211226133206](https://user-images.githubusercontent.com/69413623/147399904-599a1b27-ae91-489f-b055-5edcd0684db8.png)
ut please report this error.

**Comment by Lusamine** [comment]
You currently need the [development build of PKHeX](https://projectpokemon.org/home/files/file/2445-pkhex-development-build/) until a new stable PKHeX is released.

Download the development build, unzip it, and move your plugins folder in.

If you can't get it to work, the stable release should be out soon.
