### ISSUE TITLE
I can't generate a LivingDex or Smogon Sets

### ISSUE THREAD

**Issue by TemporalUserForBugs** [architdate/PKHeX-Plugins#139]
**Describe the bug**
An error screen appears when I´m trying to generate a LivingDex or Smogon Sets. As simple as that.
I paste here what appears in the error window

Exception Details:
System.AggregateException: One or more errors occurred. ---> System.MissingMethodException: Method not found: 'Int32 PKHeX.Core.EncounterStatic.get_FlawlessIVCount()'.
   at PKHeX.Core.AutoMod.APILegality.PreSetPIDIV(PKM pk, IEncounterable enc, IBattleTemplate set)
   at PKHeX.Core.AutoMod.APILegality.GetLegalFromTemplate(ITrainerInfo dest, PKM template, IBattleTemplate set, LegalizationResult& satisfied)
   at PKHeX.Core.AutoMod.APILegality.<>c__DisplayClass96_0.<GetLegalFromTemplateTimeout>g__GetLegal|0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PKHeX.Core.AutoMod.APILegality.<TimeoutAfter>d__98.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at PKHeX.Core.AutoMod.APILegality.GetLegalFromTemplateTimeout(ITrainerInfo dest, PKM template, IBattleTemplate set, LegalizationResult& satisfied)
   at PKHeX.Core.AutoMod.Legalizer.TryAPIConvert(ITrainerInfo tr, IBattleTemplate set, PKM template, PKM& pkm)
   at PKHeX.Core.AutoMod.ModLogic.GetRandomEncounter(PKM blank, ITrainerInfo tr, Int32 species, Nullable`1 form, Boolean shiny, Boolean alpha, Int32& attempt)
   at PKHeX.Core.AutoMod.ModLogic.GetRandomEncounter(ITrainerInfo tr, Int32 species, Nullable`1 form, Boolean shiny, Boolean alpha, Int32& attempt, PKM& pk)
   at PKHeX.Core.AutoMod.ModLogic.AddPKM(SaveFile sav, ITrainerInfo tr, List`1 pklist, Int32 species, Nullable`1 form, Boolean shiny, Boolean alpha, Int32& attempt)
   at PKHeX.Core.AutoMod.ModLogic.GenerateLivingDex(SaveFile sav, IEnumerable`1 speciesIDs, Boolean includeforms, Boolean shiny, Boolean alpha, Int32& attempts)
   at PKHeX.Core.AutoMod.ModLogic.GenerateLivingDex(SaveFile sav, Int32& attempts)
   at AutoModPlugins.LivingDex.GenLivingDex(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.MissingMethodException: Method not found: 'Int32 PKHeX.Core.EncounterStatic.get_FlawlessIVCount()'.
   at PKHeX.Core.AutoMod.APILegality.PreSetPIDIV(PKM pk, IEncounterable enc, IBattleTemplate set)
   at PKHeX.Core.AutoMod.APILegality.GetLegalFromTemplate(ITrainerInfo dest, PKM template, IBattleTemplate set, LegalizationResult& satisfied)
   at PKHeX.Core.AutoMod.APILegality.<>c__DisplayClass96_0.<GetLegalFromTemplateTimeout>g__GetLegal|0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PKHeX.Core.AutoMod.APILegality.<TimeoutAfter>d__98.MoveNext()<---

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

PKHeX, Version=22.3.1.0, Culture=neutral, PublicKeyToken=null
C:\Users\user\Desktop\Desktop\PKHeX (210521)\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll

System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

System.Reflection, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Reflection\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Reflection.dll

System.Runtime.InteropServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.dll

System.Runtime.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Extensions\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Extensions.dll

Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed

System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll

System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll

System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll

PKHeX.Drawing.PokeSprite, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.Windows.Forms.resources, Version=4.0.0.0, Culture=es, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms.resources\v4.0_4.0.0.0_es_b77a5c561934e089\System.Windows.Forms.resources.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.ValueTuple, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ValueTuple\v4.0_4.0.0.0__cc7b13ffcd2ddd51\System.ValueTuple.dll

PKHeX.Drawing.Misc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

AutoModPlugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\user\Desktop\Desktop\PKHeX (210521)\plugins\AutoModPlugins.dll

PKHeX.Core.Injection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

QRPlugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\User\user\Desktop\Desktop\PKHeX (210521)\plugins\QRPlugins.dll

PKHeX.Core.AutoMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

Microsoft.GeneratedCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
An error occurred while listing the Loaded Assemblies:
System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
   at System.Reflection.Emit.InternalAssemblyBuilder.get_Location()
   at PKHeX.WinForms.ErrorWindow.UpdateExceptionDetailsMessage()
--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

**To Reproduce**
1. Go to 'Tools'
2. Click on 'Auto Legality Mod'
3. Click on 'Generate Living Dex'
4. Click 'Yes'
5. See error

**Expected behavior**
Just generate a Living Dex

**Screenshots**
![image](https://user-images.githubusercontent.com/101025437/156934062-1f389876-c2f8-41e4-8bed-71e054156b66.png)

**Additional context**
This happened after updating the plugins.

**Comment by Lusamine** [comment]
"Method Not Found" is on the Wiki under Troubleshooting.
https://github.com/architdate/PKHeX-Plugins/wiki/FAQ-and-Troubleshooting

You are on PKHeX version 2022.03.01, and the latest release is for an older version.
![image](https://user-images.githubusercontent.com/30205550/156934272-a0f5e1a8-ac1b-487e-9393-37c700372bb6.png)
You can go to Project Pokemon to download an older version of PKHeX.

This isn't a bug. It's expected behavior when you use mismatched plugins with PKHeX.

**Comment by TemporalUserForBugs** [comment]
Thanks! I'm new here, so, sorry for the bad label.
