### ISSUE TITLE
Not able To Generate a Living Dex

### ISSUE THREAD

**Issue by Cookieiguess** [architdate/PKHeX-Plugins#140]
I can't create a living Pokédex in pokémon ultramoon (The App-icon also isn't supposed to be blue right i used the almsetup-stable to download it but i got the same error when the icon was red)

1. Open PKHeX
2. Click on Auto-Legality-Mod
3. Scroll down to Generate Living dex

I don't have a screenshot but i think if i put the error window text thing here it should work too (i hope):
Exception Details:
System.AggregateException: One or more errors occurred. ---> System.MissingMethodException: Method not found: 'Int32 PKHeX.Core.EncounterStatic.get_FlawlessIVCount()'.
   at PKHeX.Core.AutoMod.APILegality.PreSetPIDIV(PKM pk, IEncounterable enc, IBattleTemplate set)
   at PKHeX.Core.AutoMod.APILegality.GetLegalFromTemplate(ITrainerInfo dest, PKM template, IBattleTemplate set, LegalizationResult& satisfied)
   at PKHeX.Core.AutoMod.APILegality.<>c__DisplayClass96_0.<GetLegalFromTemplateTimeout>g__GetLegal|0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PKHeX.Core.AutoMod.APILegality.<TimeoutAfter>d__98.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at PKHeX.Core.AutoMod.APILegality.GetLegalFromTemplateTimeout(ITrainerInfo dest, PKM template, IBattleTemplate set, LegalizationResult& satisfied)
   at PKHeX.Core.AutoMod.Legalizer.TryAPIConvert(ITrainerInfo tr, IBattleTemplate set, PKM template, PKM& pkm)
   at PKHeX.Core.AutoMod.ModLogic.GetRandomEncounter(PKM blank, ITrainerInfo tr, Int32 species, Nullable`1 form, Boolean shiny, Boolean alpha, Int32& attempt)
   at PKHeX.Core.AutoMod.ModLogic.GetRandomEncounter(ITrainerInfo tr, Int32 species, Nullable`1 form, Boolean shiny, Boolean alpha, Int32& attempt, PKM& pk)
   at PKHeX.Core.AutoMod.ModLogic.AddPKM(SaveFile sav, ITrainerInfo tr, List`1 pklist, Int32 species, Nullable`1 form, Boolean shiny, Boolean alpha, Int32& attempt)
   at PKHeX.Core.AutoMod.ModLogic.GenerateLivingDex(SaveFile sav, IEnumerable`1 speciesIDs, Boolean includeforms, Boolean shiny, Boolean alpha, Int32& attempts)
   at PKHeX.Core.AutoMod.ModLogic.GenerateLivingDex(SaveFile sav, Int32& attempts)
   at AutoModPlugins.LivingDex.GenLivingDex(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.MissingMethodException: Method not found: 'Int32 PKHeX.Core.EncounterStatic.get_FlawlessIVCount()'.
   at PKHeX.Core.AutoMod.APILegality.PreSetPIDIV(PKM pk, IEncounterable enc, IBattleTemplate set)
   at PKHeX.Core.AutoMod.APILegality.GetLegalFromTemplate(ITrainerInfo dest, PKM template, IBattleTemplate set, LegalizationResult& satisfied)
   at PKHeX.Core.AutoMod.APILegality.<>c__DisplayClass96_0.<GetLegalFromTemplateTimeout>g__GetLegal|0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PKHeX.Core.AutoMod.APILegality.<TimeoutAfter>d__98.MoveNext()<---

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

PKHeX, Version=22.3.1.0, Culture=neutral, PublicKeyToken=null
D:\0000000000 PKHEX\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll

System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

System.Reflection, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Reflection\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Reflection.dll

System.Runtime.InteropServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.dll

System.Runtime.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Extensions\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Extensions.dll

Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed

PKHeX.Drawing.PokeSprite, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.Windows.Forms.resources, Version=4.0.0.0, Culture=de, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms.resources\v4.0_4.0.0.0_de_b77a5c561934e089\System.Windows.Forms.resources.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.ValueTuple, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ValueTuple\v4.0_4.0.0.0__cc7b13ffcd2ddd51\System.ValueTuple.dll

PKHeX.Drawing.Misc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

AutoModPlugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
D:\0000000000 PKHEX\plugins\AutoModPlugins.dll

PKHeX.Core.Injection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

QRPlugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
D:\0000000000 PKHEX\plugins\QRPlugins.dll

PKHeX.Core.AutoMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

Microsoft.GeneratedCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
An error occurred while listing the Loaded Assemblies:
System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
   at System.Reflection.Emit.InternalAssemblyBuilder.get_Location()
   at PKHeX.WinForms.ErrorWindow.UpdateExceptionDetailsMessage()
--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

**Comment by Cookieiguess** [comment]
also i don't know how to add labels or anything like that

**Comment by Lusamine** [comment]
Automatic setup won't work because the latest version of plugins isn't the same as latest version of PKHeX.  This isn't a bug; it's what happens when you use mismatched versions.

Refer to the wiki > Troubleshooting and search for your error ("Method not found") to learn how to download an older version of PKHeX that matches the version of that plugins, or wait on a new release.
