### ISSUE TITLE
ArgumentNullException when genning Smogon sets

### ISSUE THREAD

**Issue by BeyondTheHorizon** [architdate/PKHeX-Plugins#15]
Hi, thanks for #13 and really sorry to bother you again, but now when I try to import a Smogon set it returns the following error:
```
Exception Details:
System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
   at PKHeX.Core.PKMConverter.GetBlank(Type t)
   at PKHeX.Core.PKMConverter.GetBlank(Int32 gen)
   at PKHeX.Core.PKMConverter.GetBlank(Int32 gen, GameVersion ver)
   at PKHeX.Core.AutoMod.Legalizer.GetLegalFromSet(ITrainerInfo tr, ShowdownSet set, LegalizationResult& msg, Boolean allowAPI)
   at PKHeX.Core.AutoMod.Legalizer.ImportToExisting(ITrainerInfo tr, IReadOnlyList`1 sets, IList`1 arr, Int32 start, Boolean overwrite, Boolean allowAPI)
   at AutoModPlugins.ShowdownSetLoader.ImportSetsToBoxes(IReadOnlyList`1 sets, Boolean replace, Boolean allowAPI)
   at AutoModPlugins.ShowdownSetLoader.Import(IReadOnlyList`1 sets)
   at AutoModPlugins.SmogonGenner.GenSmogonSets(PKM rough)
   at AutoModPlugins.SmogonGenner.SmogonGenning(Object sender, EventArgs e)
```

**Comment by BeyondTheHorizon** [comment]
I also tried this with 19.04.02. Same error.

**Comment by kwsch** [comment]
Please post an example of what you are trying to import, because the three test cases didn't have this error.

**Comment by BeyondTheHorizon** [comment]
I just realized I said import instead of gen. That changes the whole sentence. Oops!

What I do is go to Tools → Auto Legality Mod → Gen Smogon Sets. Error!

**Comment by kwsch** [comment]
tr.Game is -1, due to games prior to SAV5 not storing the "Game ID" value in the file. Base PKHeX issue, need to think about how to best resolve it.
