### ISSUE TITLE
Legalize crashes on run.

### ISSUE THREAD

**Issue by gamerboyleo** [architdate/PKHeX-Plugins#19]
I keep clicking "Legalize Active Pokemon", but every time I do, I get this error:
```
Exception Details:
System.MissingMethodException: Method not found: 'Void PKHeX.Core.SimpleTrainerInfo..ctor(PKHeX.Core.GameVersion)'.
   at PKHeX.Core.AutoMod.APILegality.GetLegalFromTemplate(ITrainerInfo dest, PKM template, ShowdownSet set, Boolean& satisfied)
   at PKHeX.Core.AutoMod.Legalizer.Legalize(ITrainerInfo tr, PKM pk)
   at AutoModPlugins.LegalizeBoxes.LegalizeActive()
   at AutoModPlugins.LegalizeBoxes.Legalize(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

PKHeX, Version=19.11.25.0, Culture=neutral, PublicKeyToken=null
C:\Users\leobo\Downloads\PKHeX (191125)b\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null


System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null


AutoModPlugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\leobo\Downloads\PKHeX (191125)b\plugins\AutoModPlugins.dll

PKHeX.Core.AutoMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\leobo\Downloads\PKHeX (191125)b\plugins\PKHeX.Core.AutoMod.dll

System.Drawing.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing.Design\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.Design.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.
```

**Comment by architdate** [comment]
Are you using the latest commit of the plugins and the latest commit of PKHeX?

**Comment by gamerboyleo** [comment]
Yes, I just installed it before I sent this. After trying to legalize something, this happened.

**Comment by architdate** [comment]
This shouldn't happen on the latest commit of both. Keep in mind that commit is not the same as release. I suggest you download the latest pkhex commit too (not just the mod)

**Comment by gamerboyleo** [comment]
I used both.

**Comment by gamerboyleo** [comment]
Fixed: I was using an outdated version of PkHeX.
